name: Development pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  job: Install packages
    runs-on: ubuntu-20.04
    steps:
      - name: npm install
      - run: npm install
      