name: Health check

on:
  schedule:
    - cron: "* 21 * * *"

jobs:
  deployed_app_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://samo-patientor.herokuapp.com/api/ping
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
