name: Development pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd
      
      - name: package install
        run: npm install
      
      - name: lint
        run: npm run lint
      
      - name: build
        run: npm run tsc
      
      - name: test
        run: npm run test